### ISSUE TITLE
Cannot whisper people with Umlaut in their name

### ISSUE THREAD

**Issue by muellerj** [shirsig/WIM#1]
When trying to whisper people with names containing an Umlaut (`ä`, `ö`, `ü`), the name is truncated to the last character before the Umlaut and the `/w` fails.

Please let me know if you need further screenshots/input.

**Comment by shirsig** [comment]
Thanks, should be fixed.

**Comment by muellerj** [comment]
Awesome, just tested it. Thanks a lot for the fast response!
